## Python 102

**Scenario:** Today we are going to build upon the for loops of yesterday. Who has ever got to the cash register at costco, or whole foods, seen the total and asked "how did I spend that much?". Today we have a grocery list of items and prices, but we do not have infinite money (unfortunately), so we need to have a program that will look at our grocery list and help us manage our shopping and cost.

### Learning goals:

Today we will:
 - revisit what for loop does, using a dictionary
 - use `break` to adjust loop activity
 - use nested loops to navigate a nested dictionary
 - write a robust function that will take any nested dictionary of items, costs, and print out your shopping list, stopping when the total cost gets to high, and telling you the average cost per item in your cart.

Let's revisit what a for loop does. Here we have a list of items, and a separate list of costs. We are going to write a loop to print each item, it's cost, and the total of our grocery list.

```
items = ['cheese', 'whole milk', 'kefir', 'tofu four-pack', 'kale', 'oranges', 'ham', 'ben & jerry's']
cost = [2.79, 3.42, 4.50, 12.00, 2.75, 3.64, 25.00, 5.29]
```

![groc-cart](https://images.pexels.com/photos/1389103/pexels-photo-1389103.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260)

### For loops:
First, let's create a for-loop that prints each item in the list with "I need to buy: " item.

In [4]:
items = ['cheese', 'whole milk', 'kefir', 'tofu four-pack', 'kale', 'oranges', 'ham', '''ben & jerry's''']  
# '''''', super quote
cost = [2.79, 3.42, 4.50, 12.00, 2.75, 3.64, 25.00, 5.29]

In [5]:
for item in items:
    print (f'I need to buy {item}')

I need to buy cheese
I need to buy whole milk
I need to buy kefir
I need to buy tofu four-pack
I need to buy kale
I need to buy oranges
I need to buy ham
I need to buy ben & jerry's


Let's make that a little nicer looking:

```
print("I need to buy: ")
for item in items:
   print(" - [ ] ", item)
```

Okay, we want to work through a dictionary, so what's one way to convert those two lists to a dictionary?

_Hint_: Check [this](https://www.w3schools.com/python/ref_func_zip.asp) documentation. 

In [7]:
print ('I need to buy: ')
for item in items:
   print(" - [ ] ", item)  # - [ ] syntax for checklist in markdown

I need to buy: 
 - [ ]  cheese
 - [ ]  whole milk
 - [ ]  kefir
 - [ ]  tofu four-pack
 - [ ]  kale
 - [ ]  oranges
 - [ ]  ham
 - [ ]  ben & jerry's


In [11]:
list(zip(items,cost))  # if you have additional element in either list, it will still work

[('cheese', 2.79),
 ('whole milk', 3.42),
 ('kefir', 4.5),
 ('tofu four-pack', 12.0),
 ('kale', 2.75),
 ('oranges', 3.64),
 ('ham', 25.0),
 ("ben & jerry's", 5.29)]

In [12]:
grocery_dict = dict(zip(items,cost))

In [15]:
for key, val in grocery_dict.items():
    print(f'{key} costs $ {val}')

cheese costs $ 2.79
whole milk costs $ 3.42
kefir costs $ 4.5
tofu four-pack costs $ 12.0
kale costs $ 2.75
oranges costs $ 3.64
ham costs $ 25.0
ben & jerry's costs $ 5.29


So let's now add the total grocery bill at the end:

In [13]:
total =0 
for value in grocery_dict.values():
    total += value
total == sum(cost)

True

Does this look reasonable?

What if you only had $25? 

How can you build it out to stop adding items when the total is over $25?

### While, break, and continue
What does a while loop look like in Python?

In [16]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


- What is break and continue?
- Are they different? How?
- Run the following code:

In [17]:
name = 'Andy'
while name:
    print(name)
    name = name[:-1]

Andy
And
An
A


In [ ]:
# Falsey things in python
''
[]
{}
()
False
0
None

In [21]:
eggs = 0
while eggs < 6:
  eggs += 1
  if eggs == 3:
    print("spam")
    continue
  print(eggs)

1
2
spam
4
5
6


How does the code above work?

Now run this code:

In [22]:
eggs = 0
while eggs < 6:
  eggs += 1
  if eggs == 3:
    print("spam")
    break
  print(eggs)

1
2
spam


Why is the output different?

It stopped at foo, why?

We can also include `breaks` in for-loops.

What would we use to **stop** the for loop if the total reached $25?

In [26]:
total =0 
for key, value in grocery_dict.items():
    if total + val > 25:
        continue
    total += value
    print(key)
total

cheese
whole milk
kefir
tofu four-pack


22.71

What if we wanted to use continue and break to stop the program if an item costs more than **$10** ?

### Nested Loops

In [28]:
list2 = [1,2,3,4,5]
list3 = ['a','b','c','d','e']
for x in list2:
  print('row:', x)
  for y in list3:
    print('coumn', y)

row: 1
coumn a
coumn b
coumn c
coumn d
coumn e
row: 2
coumn a
coumn b
coumn c
coumn d
coumn e
row: 3
coumn a
coumn b
coumn c
coumn d
coumn e
row: 4
coumn a
coumn b
coumn c
coumn d
coumn e
row: 5
coumn a
coumn b
coumn c
coumn d
coumn e


What do you expect to see? Why?

Here's a more complicated example, what is it doing?

In [29]:
i = 2
while(i < 100):
   j = 2
   while(j <= (i/j)):
      if not(i%j): break
      j = j + 1
   if (j > i/j) : print( i, " is prime")
   i = i + 1

print ("Good bye!")

2  is prime
3  is prime
5  is prime
7  is prime
11  is prime
13  is prime
17  is prime
19  is prime
23  is prime
29  is prime
31  is prime
37  is prime
41  is prime
43  is prime
47  is prime
53  is prime
59  is prime
61  is prime
67  is prime
71  is prime
73  is prime
79  is prime
83  is prime
89  is prime
97  is prime
Good bye!


Here is a more robust shopping list of nested dictionaries:
```
shopping_dict = {'Grocieries': {'ben & jerrys': 5.29, 'cheese': 2.79,'ham': 25.0, 'kale': 2.75,'kefir': 4.5,'oranges': 3.64,'tofu four-pack': 12.0,'whole milk': 3.42},
                 'House supplies': {'toilet paper pack': 16.50, 'clorox spray': 6.43, 'kleenex': 2.50,},
                 'Pet supplies': {'Taste of the Wild': 65.20, 'squeaky toy': 4.50, 'duck feet': 8.45}}
```

write the nested for loops to print out each grocery list with its total

_Hint_

- use [this link](https://pyformat.info/#number) for help in formatting the total to two decimal places

In [ ]:
total = 0
for item in shopping_dict.items():
    

In [30]:
shopping_dict = {'Grocieries': {'ben & jerrys': 5.29, 'cheese': 2.79,'ham': 25.0, 'kale': 2.75,'kefir': 4.5,'oranges': 3.64,'tofu four-pack': 12.0,'whole milk': 3.42},
                 'House supplies': {'toilet paper pack': 16.50, 'clorox spray': 6.43, 'kleenex': 2.50,},
                 'Pet supplies': {'Taste of the Wild': 65.20, 'squeaky toy': 4.50, 'duck feet': 8.45}}


In [36]:
total = 0
for k,v in shopping_dict.items():
    for k1,v2 in v.items():
        total += v2
        print(f'{k} item {k1} cost ${v2}.\
        total cost is {total}')
print(total)

Grocieries item ben & jerrys cost $5.29.        total cost is 5.29
Grocieries item cheese cost $2.79.        total cost is 8.08
Grocieries item ham cost $25.0.        total cost is 33.08
Grocieries item kale cost $2.75.        total cost is 35.83
Grocieries item kefir cost $4.5.        total cost is 40.33
Grocieries item oranges cost $3.64.        total cost is 43.97
Grocieries item tofu four-pack cost $12.0.        total cost is 55.97
Grocieries item whole milk cost $3.42.        total cost is 59.39
House supplies item toilet paper pack cost $16.5.        total cost is 75.89
House supplies item clorox spray cost $6.43.        total cost is 82.32
House supplies item kleenex cost $2.5.        total cost is 84.82
Pet supplies item Taste of the Wild cost $65.2.        total cost is 150.01999999999998
Pet supplies item squeaky toy cost $4.5.        total cost is 154.51999999999998
Pet supplies item duck feet cost $8.45.        total cost is 162.96999999999997
162.96999999999997


In [33]:
shopping_dict['Grocieries']['cheese']

2.79

### Functions

**Built-in functions** <br>
Many useful functions are already built into Python:<br>

`print()`: print the given string or variable's value<br>
`type()`: returns the datatype of the argument<br>
`len()`: returns the length of an array<br>
`sum()`: returns the sum of the array's values<br>
`min()`: returns the smallest member of an array <br>
`max()`: returns the largest member of an array<br>


**Writing your own functions**

```
def sayHello():
  print("Hello!")
```
How do we run it?

```
sayHello()
```

Let's talk about arguments or parameters. Let's say we want to make this function more dynamic and print out whatever we want! How would we do that?
```
def shout(phrase):
  print(phrase + "!!!")
shout("oh hai")
```

In [37]:
def shout(phrase):
  print(phrase + "!!!")
shout("oh hai")

oh hai!!!


What if we don't pass in an argument? What happens?
Maybe we can establish a default value for the argument in case it isn't passed in.

```
def shout(phrase = "oh hai"):
  print(phrase + "!!!")

shout()
shout("bye")
```

In [38]:
def shout(phrase = "oh hai"):
  print(phrase + "!!!")

shout()
shout("bye")

oh hai!!!
bye!!!


What if we wanted to run a function, take its output and put it in to another function?

```
def add_one(number):
  return number + 1

def times_five(number):
  return number * 5

number_plus_one = add_one(1)
answer = times_five(number_plus_one)
print(answer)
```

What will the above code return?

In [39]:
def add_one(number):
  return number + 1

def times_five(number):
  return number * 5

number_plus_one = add_one(1)
answer = times_five(number_plus_one)
print(answer)

10


Adapt your shopping list nested for-loop to be wrapped in a function you could call on any shopping list of nested dictionaries.

In [41]:
def shop_list(shop_dict):
    total = 0
    for category, goods in shop_dict.items():
        for subgoods, price in goods.items():
            total += price
            print(f'{category} item {subgoods} cost ${price}.\
        so far total cost is {total}')
    return total
shop_list(shopping_dict)

Grocieries item ben & jerrys cost $5.29.        so far total cost is 5.29
Grocieries item cheese cost $2.79.        so far total cost is 8.08
Grocieries item ham cost $25.0.        so far total cost is 33.08
Grocieries item kale cost $2.75.        so far total cost is 35.83
Grocieries item kefir cost $4.5.        so far total cost is 40.33
Grocieries item oranges cost $3.64.        so far total cost is 43.97
Grocieries item tofu four-pack cost $12.0.        so far total cost is 55.97
Grocieries item whole milk cost $3.42.        so far total cost is 59.39
House supplies item toilet paper pack cost $16.5.        so far total cost is 75.89
House supplies item clorox spray cost $6.43.        so far total cost is 82.32
House supplies item kleenex cost $2.5.        so far total cost is 84.82
Pet supplies item Taste of the Wild cost $65.2.        so far total cost is 150.01999999999998
Pet supplies item squeaky toy cost $4.5.        so far total cost is 154.51999999999998
Pet supplies item d

162.96999999999997

### Mathematical Notation and Measures of Central Tendency 

median vs mode vs mean<br>
What's the difference?


`samp_list = [1,1,1,1,2,2,2,3,3,10,44]`

How could you write a for loop to calculate the mean?

In [43]:
samp_list = [1,1,1,1,2,2,2,3,3,10,44]
total = 0
for num in samp_list:
    total += num
avg = total/len(samp_list)

avg == sum(samp_list)/len(samp_list)

True

### Integration

adapt your function to do the following:
- stop the nested loop if a grocery total goes over $30
- print out the average cost of per item in your cart

In [48]:
def shop_under30(shop_dict):
    total = 0
    for category, goods in shop_dict.items():
        for subgoods, price in goods.items():
            if total + price > 30:
                continue
            total += price
            print(f'{category} item {subgoods} cost ${price}.\
        so far total cost is {total}')
    return total
shop_under30(shopping_dict)

Grocieries item ben & jerrys cost $5.29.        so far total cost is 5.29
Grocieries item cheese cost $2.79.        so far total cost is 8.08
Grocieries item kale cost $2.75.        so far total cost is 10.83
Grocieries item kefir cost $4.5.        so far total cost is 15.33
Grocieries item oranges cost $3.64.        so far total cost is 18.97
Grocieries item whole milk cost $3.42.        so far total cost is 22.39
House supplies item clorox spray cost $6.43.        so far total cost is 28.82


28.82

In [53]:
def avg_cost(shop_cart):
    total = 0
    num = 0
    for category, goods in shop_cart.items():
        for subgoods, price in goods.items():
            total += price
            num += 1
    return round(total/num,2)
avg_cost(shopping_dict)

11.64

## Jupyter Bonus

This doesn't really fit in with the rest of Python 102, but Jupyter is incredibly flexible! Here are two examples of embedding beautiful LaTex scripting in a notebook.

In [54]:
%%latex # this will make the entire cell LaTeX syntax
$$\lim\limits_{x \to \infty} \exp(-x) = 0$$

<IPython.core.display.Latex object>

In [55]:
from IPython.display import Math
# this imports a function called Math() in which you can pass in a raw string of LaTeX
Math('F(k) = \int_{-\infty}^{\infty} f(x) e^{2\pi i k} dx')

<IPython.core.display.Math object>